### ISSUE TITLE
userAgentParser bug? (exceptions.ValueError: invalid literal for float(): 5.1.1)

### ISSUE THREAD

**Issue by florian-asche** [janrueth/SiriServerCore#102]
Hi,

i installed SiriServerCore on Debian 6. I used an iPhone 4, Version 5.1.1.

An old Version of SiriServerCore running fine, this new Version have some Problem with the new userAgentParser.

---

siri:~/SiriServerCore# python SiriServer.py
INFO Starting server on port 4443
INFO Loading Session Certificates
INFO Setting Up Database
INFO Connection to Database
INFO Loading Plugin Framework
INFO Server is running and listening for connections
INFO New connection from 192.168.0.51 on port 49343
INFO Currently 1 clients connected
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 59, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 37, in callWithContext
    return func(_args,_*kw)
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/internet/epollreactor.py", line 217, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib/python2.6/dist-packages/twisted/internet/tcp.py", line 137, in doRead
    return Connection.doRead(self)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/tcp.py", line 460, in doRead
    return self.protocol.dataReceived(data)
  File "/usr/lib/python2.6/dist-packages/twisted/protocols/basic.py", line 251, in dataReceived
    why = self.lineReceived(line)
  File "/root/SiriServerCore/SiriCore.py", line 121, in lineReceived
    self.clientOSVersion = float(match.group('clientOSVersion'))
exceptions.ValueError: invalid literal for float(): 5.1.1
## ERROR Connection Lost: [Failure instance: Traceback (failure with no frames): <type 'exceptions.ValueError'>: invalid literal for float(): 5.1.1

siri:~/SiriServerCore# python -V
Python 2.6.6

Note:
The jimmykane / SiriServerCore fork (https://github.com/jimmykane/SiriServerCore) is working fine. But you know.... Always use the newest version ;)

**Comment by janrueth** [comment]
Thanks for the bugreport, I already spotted my mistake, I did not assume minor versions in iOS, will change this to a string from a float. I will push a fix when I'm back home this evening (GMT+1)

**Comment by janrueth** [comment]
I just pushed a fix!
