### ISSUE TITLE
Uh...

### ISSUE THREAD

**Issue by andymcblane** [janrueth/SiriServerCore#109]
CRITICAL load_plugins Failed loading plugin due to missing module: 'Wordnik library not found. Please install wordnik library! e.g. sudo easy_install wordnik'
CRITICAL load_plugins Failed loading plugin due to missing API key: 'Could not find API key for: yelp. Please check your apiKeys.conf'
ERROR load_plugins Plugin loading failed
Traceback (most recent call last):
  File "/home/Andy/SiriServer/PluginManager.py", line 29, in load_plugins
    **import**(pluginPath+"."+line,  globals(), locals(), [], -1)
  File "/home/Andy/SiriServer/plugins/googleVoice/**init**.py", line 7, in <module>
    from googlevoice import Voice
ImportError: No module named googlevoice
CRITICAL load_plugins Failed loading plugin due to missing API key: 'Could not find API key for: google. Please check your apiKeys.conf'
ERROR load_plugins Plugin loading failed
Traceback (most recent call last):
  File "/home/Andy/SiriServer/PluginManager.py", line 29, in load_plugins
    **import**(pluginPath+"."+line,  globals(), locals(), [], -1)
  File "/home/Andy/SiriServer/plugins/memebase/**init**.py", line 11, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup
ERROR load_plugins Plugin loading failed
Traceback (most recent call last):
  File "/home/Andy/SiriServer/PluginManager.py", line 29, in load_plugins
    **import**(pluginPath+"."+line,  globals(), locals(), [], -1)
  File "/home/Andy/SiriServer/plugins/wikipedia/**init**.py", line 7, in <module>
    import urllib2, nltk, json
ImportError: No module named nltk
ERROR load_plugins Plugin loading failed
Traceback (most recent call last):
  File "/home/Andy/SiriServer/PluginManager.py", line 29, in load_plugins
    **import**(pluginPath+"."+line,  globals(), locals(), [], -1)
  File "/home/Andy/SiriServer/plugins/graffiti.py", line 10, in <module>
    class test(Plugin):
  File "/home/Andy/SiriServer/plugins/graffiti.py", line 12, in test
    full_json = urllib2.urlopen(req).read()
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 1181, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.6/urllib2.py", line 1156, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 8] hostname nor servname provided, or not known>
CRITICAL load_plugins Failed loading plugin due to missing API key: 'Could not find API key for: google. Please check your apiKeys.conf'
INFO <module> Starting Server
INFO __init__ Listening on port 1024

**Comment by janrueth** [comment]
Well the server actually tells you what is wrong, so you should fix the problems... you are missing several API keys and python modules for all your plugins
