### ISSUE TITLE
Best match index out of bounds 

### ISSUE THREAD

**Issue by jimmykane** [janrueth/SiriServerCore#13]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(_args,_*kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 581, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 199, in doRead
    rval = self.protocol.dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 413, in dataReceived
    self._flushReceiveBIO()
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 383, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    return self.rawDataReceived(data)
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 115, in rawDataReceived
    self.process_compressed_data()
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 126, in process_compressed_data
    self.received_plist(plist)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 168, in received_plist
    self.process_recognized_speech({u'hypotheses': [{'confidence': 1.0, 'utterance': plist['properties']['utterance']}]}, plist['aceId'], False)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 60, in process_recognized_speech
    best_match = best_match[0].upper()+best_match[1:]
exceptions.IndexError: string index out of range

**Comment by janrueth** [comment]
fixed
