### ISSUE TITLE
New commits breaks core

### ISSUE THREAD

**Issue by snxraven** [janrueth/SiriServerCore#15]
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1167, i                                                                              n mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 762, in                                                                               runUntilCurrent
    f(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 361, i                                                                              n callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 455, i                                                                              n _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 542, i                                                                              n _runCallbacks
    current.result = callback(current.result, _args, *_kw)
  File "/root/siriServers/test/SiriProtocolHandler.py", line 74, in handle_googl                                                                              e_data
    self.process_recognized_speech(googleAnswer, requestId, dictation)
  File "/root/siriServers/test/SiriProtocolHandler.py", line 89, in process_reco                                                                              gnized_speech
    if len(best_match == 1):
exceptions.TypeError: object of type 'bool' has no len()

**Comment by snxraven** [comment]
Fixxed *\* :"P

**Comment by janrueth** [comment]
fixed
