### ISSUE TITLE
Timeout already called

### ISSUE THREAD

**Issue by jimmykane** [janrueth/SiriServerCore#16]
Unhandled Error
Traceback (most recent call last):
  File "SiriServer.py", line 228, in <module>
    main()
  File "SiriServer.py", line 224, in main
    reactor.run()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1169, in run
    self.mainLoop()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1178, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 800, in runUntilCurrent
    call.func(_call.args, *_call.kw)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 68, in checkTimeout
    self.timeoutschedule.reset(SiriProtocolHandler.__timeout_delay)
  File "/usr/lib64/python2.7/site-packages/twiste

**Comment by janrueth** [comment]
okaaay... will fix that if I know why it is doing so :D

**Comment by janrueth** [comment]
should be fixed, push will come soon
