### ISSUE TITLE
Another one, I know that it handles exceptions but need to post here to look better and remember the log

### ISSUE THREAD

**Issue by jimmykane** [janrueth/SiriServerCore#23]
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 545, in _runCallbacks
    current.result = callback(current.result, _args, *_kw)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 74, in handle_google_data
    self.process_recognized_speech(googleAnswer, requestId, dictation)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 112, in process_recognized_speech
    self.send_object(recognized)
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 158, in send_object
    self.send_plist(obj.to_plist())
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 161, in send_plist
    self.sendLock.acquire()
exceptions.AttributeError: 'NoneType' object has no attribute 'acquire'

**Comment by janrueth** [comment]
Can you tell me when this happens?

**Comment by jimmykane** [comment]
Nope I am not sure, Just reporting. I had a very busy week and if I get lucky I will leave Greece and go to Holland for migration. Here the Country is F%#%# up, Sorry for the irrelevant stuff Jan, but I had to say that ouf....

To the point, I am just res posting another one 

ERROR Unexpected error during plugin processing
Traceback (most recent call last):
  File "/GoogleApi/SiriServerCore/plugin.py", line 103, in run
    self.**method(self, self.__speech, self.__lang, self.__method.__dict**[**criteria_key**][self.__lang].match(self.__speech))
  File "/GoogleApi/SiriServerCore/plugins/wolfram.py", line 199, in wolfram
    self.say("Nothing has found for your query!")
  File "/GoogleApi/SiriServerCore/plugin.py", line 225, in say
    self.send_object(view)
  File "/GoogleApi/SiriServerCore/plugin.py", line 175, in send_object
    self.__send_object(obj)
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 158, in send_object
    self.send_plist(obj.to_plist())
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 161, in send_plist
    self.sendLock.acquire()
AttributeError: 'NoneType' object has no attribute 'acquire'

Just to keep track of that. I hope I get some time soon, to get into this.

**Comment by janrueth** [comment]
Does this also happen with the newest version where plugins can be aborted?

**Comment by jimmykane** [comment]
Latest version fixed the above but still lock problems in dictation

INFO Best matching result: "Text babe" with a confidence of 93.72%
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1178, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 773, in runUntilCurrent
    f(_a, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 362, in callback
    self._startRunCallbacks(result)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 458, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 545, in _runCallbacks
    current.result = callback(current.result, _args, *_kw)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 74, in handle_google_data
    self.process_recognized_speech(googleAnswer, requestId, dictation)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 112, in process_recognized_speech
    self.send_object(recognized)
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 159, in send_object
    self.send_plist(obj.to_plist())
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 162, in send_plist
    self.sendLock.acquire()
exceptions.AttributeError: 'NoneType' object has no attribute 'acquire'

**Comment by janrueth** [comment]
can you give complete debug output of all send packets?

**Comment by jimmykane** [comment]
Yes will dump the output soon

**Comment by janrueth** [comment]
I also got this error today when debugging the open file issues. It happens when the connection is lost but either a google request is still running in background or there is still data to read. I think i will be able to fix this today

**Comment by janrueth** [comment]
pushed the fix, try it please and report

**Comment by jimmykane** [comment]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(_args,_*kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 581, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 199, in doRead
    rval = self.protocol.dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 413, in dataReceived
    self._flushReceiveBIO()
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 383, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    return self.rawDataReceived(data)
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 121, in rawDataReceived
    self.process_compressed_data()
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 132, in process_compressed_data
    self.received_plist(plist)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 241, in received_plist
    (decoder, encoder, dictation) = self.speech[finishSpeech.refId]
exceptions.UnboundLocalError: local variable 'finishSpeech' referenced before assignment
WARNING Connection Lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
I

**Comment by janrueth** [comment]
Ups, yeah, must have missed that one, forgot to rename, will push a fix asap

**Comment by jimmykane** [comment]
I think now it's ok so far! after the latest commit

**Comment by jimmykane** [comment]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(_args,__kw)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/internet/posixbase.py", line 581, in _doReadOrWrite
    why = selectable.doRead()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/tcp.py", line 199, in doRead
    rval = self.protocol.dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 413, in dataReceived
    self._flushReceiveBIO()
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/tls.py", line 383, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
    return self.rawDataReceived(data)
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 121, in rawDataReceived
    self.process_compressed_data()
  File "/GoogleApi/SiriServerCore/SiriCore.py", line 132, in process_compressed_data
    self.received_plist(plist)
  File "/GoogleApi/SiriServerCore/SiriProtocolHandler.py", line 246, in received_plist
    encoder.destory()
exceptions.AttributeError: Encoder instance has no attribute 'destory'
*_\* glibc detected **\* /usr/bin/python2.7: double free or corruption (!prev): 0x0000000005d7a430 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x78aa8)[0x2ad1c0f97aa8]
/lib64/libc.so.6(cfree+0x6c)[0x2ad1c0f9c98c]
/usr/lib64/libffi.so.5(ffi_call_unix64+0x4c)[0x2ad1c5b0c124]
/usr/lib64/libffi.so.5(ffi_call+0x203)[0x2ad1c5b0bf23]
/usr/lib64/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x2c7)[0x2ad1c58f2ad7]
/usr/lib64/python2.7/lib-dynload/_ctypes.so(+0xb629)[0x2ad1c58ec629]
/usr/lib64/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2ad1c09895d3]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x491d)[0x2ad1c0a2123d]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6206)[0x2ad1c0a22b26]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6206)[0x2ad1c0a22b26]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(+0x71542)[0x2ad1c09af542]
/usr/lib64/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2ad1c09895d3]
/usr/lib64/libpython2.7.so.1.0(+0x5a4ef)[0x2ad1c09984ef]
/usr/lib64/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2ad1c09895d3]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x491d)[0x2ad1c0a2123d]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6206)[0x2ad1c0a22b26]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6206)[0x2ad1c0a22b26]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x522e)[0x2ad1c0a21b4e]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(+0x7164b)[0x2ad1c09af64b]
/usr/lib64/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2ad1c09895d3]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x418b)[0x2ad1c0a20aab]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(+0x7164b)[0x2ad1c09af64b]
/usr/lib64/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2ad1c09895d3]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x418b)[0x2ad1c0a20aab]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(+0x7164b)[0x2ad1c09af64b]
/usr/lib64/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2ad1c09895d3]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x418b)[0x2ad1c0a20aab]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(+0x7164b)[0x2ad1c09af64b]
/usr/lib64/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2ad1c09895d3]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x418b)[0x2ad1c0a20aab]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x522e)[0x2ad1c0a21b4e]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6206)[0x2ad1c0a22b26]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6206)[0x2ad1c0a22b26]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x522e)[0x2ad1c0a21b4e]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6206)[0x2ad1c0a22b26]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x88d)[0x2ad1c0a2388d]
/usr/lib64/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x2ad1c0a239a2]
/usr/lib64/libpython2.7.so.1.0(+0xffafc)[0x2ad1c0a3dafc]
/usr/lib64/libpython2.7.so.1.0(PyRun_FileExFlags+0x90)[0x2ad1c0a3e930]
/usr/lib64/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0x1ff)[0x2ad1c0a3f50f]
/usr/lib64/libpython2.7.so.1.0(Py_Main+0xb53)[0x2ad1c0a50823]
/lib64/libc.so.6(__libc_start_main+0xe6)[0x2ad1c0f41256]
/usr/bin/python2.7[0x4008a9]

**Comment by janrueth** [comment]
will look at this later
