### ISSUE TITLE
"NoneType" has no attribute "compress"

### ISSUE THREAD

**Issue by blast-hardcheese** [janrueth/SiriServerCore#56]
This only happens occasionally, but I'm worried about server stability if I'm not at home to restart it. Can someone more familiar with the protocol take a look at this? I'm available for testing.

```
INFO Request handled by: shortMessaging.sendSMS
WARNING This class is deprecated use the AB version instead
WARNING This class is deprecated use the AB version instead
INFO Sending flac to google for recognition
INFO Best matching result: "Hey how's it going" with a confidence of 96.99%
INFO Sending flac to google for recognition
INFO Best matching result: "No" with a confidence of 79.93%
INFO Sending flac to google for recognition
INFO Best matching result: "Change it" with a confidence of 77.5%
INFO Sending flac to google for recognition
INFO Best matching result: "Hey, how is it going" with a confidence of 87.89%
INFO Sending flac to google for recognition
INFO Best matching result: "Nope" with a confidence of 53.47%
INFO Sending flac to google for recognition
INFO Best matching result: "Change it" with a confidence of 51.94%
uINFO Sending flac to google for recognition
INFO Best matching result: "Hey, how's it going?" with a confidence of 95.81%
INFO Sending flac to google for recognition
INFO Best matching result: "Nope" with a confidence of 25.39%
ERROR Connection Lost: [Failure instance: Traceback: <class 'OpenSSL.SSL.SysCallError'>: (0, 'Error')
/home/blast_hardcheese/Projects/siri/sirienv/local/lib/python2.7/site-packages/twisted/python/context.py:81:callWithContext
/home/blast_hardcheese/Projects/siri/sirienv/local/lib/python2.7/site-packages/twisted/internet/posixbase.py:586:_doReadOrWrite
/home/blast_hardcheese/Projects/siri/sirienv/local/lib/python2.7/site-packages/twisted/internet/tcp.py:199:doRead
/home/blast_hardcheese/Projects/siri/sirienv/local/lib/python2.7/site-packages/twisted/protocols/tls.py:413:dataReceived
--- <exception caught here> ---
/home/blast_hardcheese/Projects/siri/sirienv/local/lib/python2.7/site-packages/twisted/protocols/tls.py:352:_flushReceiveBIO
]
INFO Currently 0 clients connected
ERROR Unexpected error during plugin processing
Traceback (most recent call last):
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/plugin.py", line 149, in run
    self.__method(self, self.__speech, self.__lang, self.__method.__dict__[__criteria_key__][self.__lang].match(self.__speech))
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/plugins/shortMessage/__init__.py", line 571, in sendSMS
    self.message(self.findPhoneForNumberType(personToMessage, None, lang), personToMessage, lang)
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/plugins/shortMessage/__init__.py", line 410, in message
    instruction = self.askForClarification(smsObj, language).strip().lower()
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/plugins/shortMessage/__init__.py", line 360, in askForClarification
    response = self.getResponseForRequest(createAnchor)
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/plugin.py", line 267, in getResponseForRequest
    self.send_object(clientBoundCommand)
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/plugin.py", line 234, in send_object
    self.__send_object(obj)
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/SiriCore.py", line 159, in send_object
    self.send_plist(obj.to_plist())
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/SiriCore.py", line 167, in send_plist
    self.flush_unzipped_output()
  File "/home/blast_hardcheese/Projects/siri/SiriServerCore/SiriCore.py", line 177, in flush_unzipped_output
    self.output_buffer += self.compressor.compress(self.unzipped_output_buffer)
AttributeError: 'NoneType' object has no attribute 'compress'
INFO New connection from 192.168.0.1 on port 60354
INFO Currently 1 clients connected
```

**Comment by janrueth** [comment]
exception SysCallError
          The SysCallError occurs when there's an I/O error and OpenSSL's
          error queue does not contain any information. This can mean two
          things: An error in the transport protocol, or an end of file
          that violates the protocol. The parameter to the exception is
          always a pair (errnum, errstr).

I can't tell why this occurs.

**Comment by blast-hardcheese** [comment]
Have you seen this before, or could this be something having to do with my setup?

**Comment by janrueth** [comment]
I haven't seen this before, I would just from the first guess recommend updating openssl components if possible
