### ISSUE TITLE
exceptions.AttributeError: 'NoneType' object has no attribute '__name__' 

### ISSUE THREAD

**Issue by spang11ers** [janrueth/SiriServerCore#59]
Hi all,

I get the following error when my server attempts to interpret a query; it was working and then it stopped after I played around with language. However since then I have put a free copy of the SiriServerCore on and it still wont work :( Can anyone help?

INFO Best matching result: "Test" with a confidence of 81.84%
Unhandled error in Deferred:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/twisted/internet/base.py", line 1174, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.6/dist-packages/twisted/internet/base.py", line 769, in runUntilCurrent
    f(_a, *_kw)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 318, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 424, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 441, in _runCallbacks
    self.result = callback(self.result, _args, *_kw)
  File "/SiriServerCore/SiriProtocolHandler.py", line 93, in handle_google_data
    self.process_recognized_speech(googleAnswer, requestId, dictation)
  File "/SiriServerCore/SiriProtocolHandler.py", line 119, in process_recognized_speech
    plugin = PluginManager.getPluginForImmediateExecution(self.assistant.assistantId, best_match, self.assistant.language, (self.send_object, self.send_plist, self.assistant, self.current_location))
  File "/SiriServerCore/PluginManager.py", line 114, in getPluginForImmediateExecution
    logger.info("Request handled by: %s.%s" % (clazz.__name__, method.**name**))
exceptions.AttributeError: 'NoneType' object has no attribute '**name**'

**Comment by spang11ers** [comment]
my Siri is set to English (United States) also

**Comment by spang11ers** [comment]
tried re installing twisted, tried different languages, tried turning siri on and off :(

**Comment by Begall** [comment]
I am also getting this error when a query fails to match anything.

**Comment by MrRoundRobin** [comment]
This patch will fix the error:

https://gist.github.com/2484400

**Comment by spang11ers** [comment]
Sorry I am a bit new at this robin, how do I apply that patch?

**Comment by janrueth** [comment]
should be fixed now
