### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'flush'

### ISSUE THREAD

**Issue by rotastrain** [janrueth/SiriServerCore#65]
Dear Eich.

This error occurs from time to time about two times a day. It is then followd by the inability of anyone to connect by giving a SSL error.
What could be the cause.and can we write a handler for it...

INFO Currently 1 clients connected
INFO Connection timed out
INFO Connection Closed: Connection was closed cleanly.
INFO Currently 0 clients connected
ERROR Unexpected error during plugin processing
Traceback (most recent call last):
  File "/home/siri/plugin.py", line 147, in run
    self.**method(self, self.__speech, self.__lang)
  File "/home/siri/plugins/hello/__init**.py", line 6, in st_name
    self.say("Hi") 
  File "/home/siri/plugin.py", line 303, in say
    self.send_object(view)
  File "/home/siri/plugin.py", line 234, in send_object
    self.__send_object(obj)
  File "/home/siri/SiriCore.py", line 159, in send_object
    self.send_plist(obj.to_plist())
  File "/home/siri/SiriCore.py", line 167, in send_plist
    self.flush_unzipped_output()
  File "/home/siri/SiriCore.py", line 179, in flush_unzipped_output
    self.output_buffer += self.compressor.flush(zlib.Z_SYNC_FLUSH)
AttributeError: 'NoneType' object has no attribute 'flush'
INFO New connection from xx.xxx.xxx.xx on port 3463
INFO Currently 1 clients connected
IWARNING SSL related error
WARNING [('SSL routines', 'SSL23_READ', 'ssl handshake failure')]
INFO Currently 0 clients connected

Restarting the server everything starts fine..

**Comment by markhack** [comment]
post here - http://ioshack.org/forums/
