### ISSUE TITLE
.py File Errors 

### ISSUE THREAD

**Issue by KyleS98** [janrueth/SiriServerCore#96]
The is the entire thing that comes up when I submit something in it.

INFO New connection from 192.168.1.149 on port 54749
INFO Currently 1 clients connected
Unhandled Error
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/python/log.py", line 84, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/python/log.py", line 69, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/python/context.py", line 81, in callWithContext
    return func(_args,_*kw)
--- <exception caught here> ---
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/selectreactor.py", line 150, in _doReadOrWrite
    why = getattr(selectable, method)()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/internet/tcp.py", line 199, in doRead
    rval = self.protocol.dataReceived(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py", line 413, in dataReceived
    self._flushReceiveBIO()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/tls.py", line 383, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/twisted/protocols/basic.py", line 572, in dataReceived
    return self.rawDataReceived(data)
  File "/Users/Kyle/APISIRI/SiriCore.py", line 126, in rawDataReceived
    self.process_compressed_data()
  File "/Users/Kyle/APISIRI/SiriCore.py", line 137, in process_compressed_data
    self.received_plist(plist)
  File "/Users/Kyle/APISIRI/SiriProtocolHandler.py", line 296, in received_plist
    fail = CommandFailed(createSessionInfoRequest.aceId)
exceptions.NameError: global name 'createSessionInfoRequest' is not defined
WARNING Connection Lost: Connection to the other side was lost in a non-clean fashion: Connection lost.
INFO Currently 0 clients connected

**Comment by rotastrain** [comment]
you need to uncomment this  line !
createSessionInfoRequest = CreateSessionInfoRequest(plist)

eich forgot to do it when he edited it.

i have made a pull request.

**Comment by janrueth** [comment]
yep, I already had that corrected locally, but I forgot to push the changes... I also added some basic sync capabilities... however it is just some basics...

**Comment by rotastrain** [comment]
Yep :) ..
I also added a similar sync to my local one but its slightly confusing and the lack of a iPhone 4S does make it harder ;) 
I can't figure out how to force the phone to send the info of contacts.im workin on it :) il make a pull if I can find anything useful

**Comment by 2cold** [comment]
#rotastrain
you need to uncomment this line !
createSessionInfoRequest = CreateSessionInfoRequest(plist)

#2cold
Are you referring to line #311 in SiriProtocolHandler.py? That's the only line that i've seen that's referring to that and the error is still present.
